### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by alien35** [ederwander/PyAutoTune#3]
This port looks awesome. Running ```python FromFileAutoTune.py ./teste.wav ./test2.wav``` returns:

FromFileAutoTune.py:52: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  while datas !='':
.
[1]    10645 segmentation fault  python FromFileAutoTune.py ./teste.wav ./test2.wav

**Comment by schanq** [comment]
I have this same issue, what was the solution?

**Comment by ederwander** [comment]
`while datas is not None:`

let me know if it works for you
