### ISSUE TITLE
Consider building wheels for PyAutoTune?

### ISSUE THREAD

**Issue by Vbbab** [ederwander/PyAutoTune#5]
Hello everyone, I would like to request for pre-built wheels (if that is possible or becomes possible in the future) for PyAutoTune, since it is a bit annoying trying to compile the sources on Windows, encountering errors like `error: Unable to find vcvarsall.bat`. I thought it might be easier for everyone if you could distribute pre-built python wheels for Windows so that people can easily install them with `pip`.

This is not necessarily an immediate issue, but (at least I feel) it could be useful to others when using `PyAutoTune`.

**Comment by ederwander** [comment]
Hi I just have python27 and python33 32bits and python37 64bits, you can find this packages here

https://github.com/ederwander/PyAutoTune/tree/master/Packages

**Comment by ederwander** [comment]
So  I rewrite some codes to make it possible to run and compile in Python3X, take a looke in the new README
