### ISSUE TITLE
Error with compiler

### ISSUE THREAD

**Issue by Tiranosaurus** [ederwander/PyAutoTune#6]
I have no idea how to resolve this error.

`c:/mingw/bin/../lib/gcc/mingw32/4.5.2/../../../../mingw32/bin/ld.exe: build\temp.win32-3.8\Release\AutoTune.cp38-win32.def:1: syntax error
c:/mingw/bin/../lib/gcc/mingw32/4.5.2/../../../../mingw32/bin/ld.exe:build\temp.win32-3.8\Release\AutoTune.cp38-win32.def: file format not recognized; treating as linker script
c:/mingw/bin/../lib/gcc/mingw32/4.5.2/../../../../mingw32/bin/ld.exe:build\temp.win32-3.8\Release\AutoTune.cp38-win32.def:1: syntax error
collect2: ld returned 1 exit status
error: command 'C:\\MinGW\\bin\\gcc.exe' failed with exit status 1
`

**Comment by ederwander** [comment]
well seems that are you compiling in python38... I haved successfull compiled it in one python37 64 bits, take a look at new README, I rewrite some code to did it works in python3X

If your python is 64bits you will need install and point the path for mingw 64bits
