### ISSUE TITLE
New README instructions for Windows might not support VS 2019

### ISSUE THREAD

**Issue by Vbbab** [ederwander/PyAutoTune#8]
I have VS 2019 compiler tools. Following your instructions in the updated README for Windows, I have put a `distutils.cfg` file in my distutils path with the following content:

```
[build]
compiler=mingw32

[build_ext]
include_dirs=C:\path\to\Python\Python38\Lib\site-packages\numpy\core\include
```

after installing MinGW, I tried running `python setup.py install` again, but it quickly exits, dumping this error:
```
ValueError: Unknown MS Compiler version 1916
```

This looks like it may be a VS tools version issue?

**Comment by ederwander** [comment]
in the file cygwinccompiler.py here it is in `C:\Python37\Lib\distutils `

find the line ` if msc_pos != -1: ` and add ms compiler version 1916

```
elif msc_ver == "1916":
     return ["vcruntime140"]
```


Search `vcruntime140.dll` in your windows and copy it to `C:\Python37\libs folder` (if your python is 64bits you need to find the corresponding file), try compile again ...

Try my `vcruntime140.dll` (for 64bits), download and copy to libs folder

https://gofile.io/d/KG3IdH

**Comment by Vbbab** [comment]
Thanks!
