### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by Tiranosaurus** [ederwander/PyAutoTune#9]
I am having a bit of a problem with the installation. I already reinstalled my mingw and added the dll file u provided in an other thread. Yet I am still getting an error.

![image](https://user-images.githubusercontent.com/42917097/89777952-f5e90100-db0c-11ea-9b78-e5514a715bf1.png)
![image](https://user-images.githubusercontent.com/42917097/89778006-0bf6c180-db0d-11ea-8d08-9fcba730f4c0.png)

**Comment by ederwander** [comment]
Incompatible type of you vcruntime witch your python ... your python is 32bits or 64bits ???

**Comment by Tiranosaurus** [comment]
I am using 64 bits

**Comment by ederwander** [comment]
this is a classic error when distutils cant find -lpython37 or when you copy the wrong vcruntime, or you are trying install using gcc incompatible

**Comment by Tiranosaurus** [comment]
Is there something I can try to test what the problem is?

**Comment by ederwander** [comment]
I am noticing this now, why are your code calling `py_string`  ? the new source not use it, seems that are you using an old version of pyautotune, download again the git pyautotune, I change some days ago the code to make it compile in python3x

**Comment by Tiranosaurus** [comment]
Thanks a lot, everything is working. 
Just one more question: is there a way to tune to a specific note?

**Comment by ederwander** [comment]
Yeahh I Haved added all notes scale 6min ago, so download and compile again ...

Scales:

```
A
a
B
b
C
D
d
e
E
F
G
g
X
```


In the example file you can change the Key note like:

`KEY="F".encode()`

`X` is chromatic scale
